// apps/mobile/src/components/GifPicker.vue
<template>
  <div v-if="visible" class="gif-overlay" @click.self="$emit('close')">
    <div class="gif-modal">
      <div class="gif-header">
        <strong>GIFs</strong>
        <button class="ghost-btn" type="button" @click="$emit('close')">Close</button>
      </div>

      <div class="gif-tabs">
        <button
          v-for="provider in providers"
          :key="provider"
          type="button"
          class="tab-btn"
          :class="{ active: activeProvider === provider }"
          @click="setProvider(provider)"
        >
          {{ provider.toUpperCase() }}
        </button>
      </div>

      <div class="gif-search">
        <input
          v-model="query"
          type="text"
          :placeholder="`Search ${activeProvider.toUpperCase()}`"
          autocomplete="off"
        />
      </div>

      <div v-if="loading" class="gif-state small">Loading GIFs...</div>
      <div v-else-if="error" class="gif-state status-danger small">{{ error }}</div>
      <div v-else-if="results.length === 0" class="gif-state small">No GIFs found.</div>

      <div v-else class="gif-grid">
        <button
          v-for="gif in results"
          :key="`${gif.provider}-${gif.id}`"
          type="button"
          class="gif-tile"
          @click="$emit('select', gif)"
        >
          <img :src="gif.previewUrl" :alt="gif.title || `${gif.provider} gif`" loading="lazy" />
        </button>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { onBeforeUnmount, ref, watch } from 'vue';
import type { GifProvider, GifResult } from '@penthouse/contracts';
import { getTrendingGifs, searchGifs } from '../services/http';

const props = defineProps<{
  visible: boolean;
}>();

defineEmits<{
  (e: 'close'): void;
  (e: 'select', gif: GifResult): void;
}>();

const providers: GifProvider[] = ['giphy', 'klipy'];
const activeProvider = ref<GifProvider>('giphy');
const query = ref('');
const results = ref<GifResult[]>([]);
const loading = ref(false);
const error = ref('');
let searchTimer: ReturnType<typeof setTimeout> | null = null;

async function loadTrending(): Promise<void> {
  loading.value = true;
  error.value = '';
  try {
    results.value = (await getTrendingGifs(activeProvider.value)).results;
  } catch (err: any) {
    error.value = err?.response?.data?.error || 'Failed to load GIFs';
    results.value = [];
  } finally {
    loading.value = false;
  }
}

async function runSearch(): Promise<void> {
  const trimmed = query.value.trim();
  if (!trimmed) {
    await loadTrending();
    return;
  }

  loading.value = true;
  error.value = '';
  try {
    results.value = (await searchGifs(activeProvider.value, trimmed)).results;
  } catch (err: any) {
    error.value = err?.response?.data?.error || 'Failed to search GIFs';
    results.value = [];
  } finally {
    loading.value = false;
  }
}

function setProvider(provider: GifProvider): void {
  if (activeProvider.value === provider) return;
  activeProvider.value = provider;
}

watch(
  () => props.visible,
  (visible) => {
    if (!visible) return;
    void loadTrending();
  }
);

watch(activeProvider, () => {
  if (!props.visible) return;
  void runSearch();
});

watch(query, () => {
  if (!props.visible) return;
  if (searchTimer) clearTimeout(searchTimer);
  searchTimer = setTimeout(() => {
    void runSearch();
  }, 250);
});

onBeforeUnmount(() => {
  if (searchTimer) clearTimeout(searchTimer);
});
</script>

<style scoped>
.gif-overlay {
  position: fixed;
  inset: 0;
  background: rgba(4, 9, 20, 0.78);
  display: flex;
  align-items: flex-end;
  justify-content: center;
  z-index: 30;
}

.gif-modal {
  width: min(100%, 720px);
  max-height: 75vh;
  background: linear-gradient(180deg, rgba(22, 33, 84, 0.98), rgba(8, 15, 42, 0.98));
  border: 1px solid rgba(255, 255, 255, 0.08);
  border-radius: 20px 20px 0 0;
  padding: 16px;
  overflow: auto;
}

.gif-header,
.gif-tabs {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 10px;
}

.gif-tabs {
  justify-content: flex-start;
  margin-top: 14px;
}

.tab-btn,
.ghost-btn {
  border: 1px solid rgba(255, 255, 255, 0.12);
  background: rgba(255, 255, 255, 0.04);
  color: var(--text);
  border-radius: 999px;
  padding: 8px 12px;
  font-size: 0.8rem;
  width: auto;
  min-width: 0;
}

.tab-btn.active {
  background: rgba(114, 214, 255, 0.18);
  border-color: rgba(114, 214, 255, 0.45);
}

.gif-search {
  margin-top: 14px;
}

.gif-search input {
  width: 100%;
}

.gif-state {
  padding: 14px 2px;
}

.gif-grid {
  margin-top: 14px;
  display: grid;
  grid-template-columns: repeat(2, minmax(0, 1fr));
  gap: 12px;
}

.gif-tile {
  padding: 0;
  border: 1px solid rgba(255, 255, 255, 0.08);
  border-radius: 14px;
  overflow: hidden;
  background: rgba(255, 255, 255, 0.03);
  min-height: 120px;
}

.gif-tile img {
  width: 100%;
  height: 100%;
  min-height: 120px;
  object-fit: cover;
  display: block;
}
</style>

// apps/web/src/lib/components/GifPicker.svelte
<script lang="ts">
	import { gifsStore } from '$stores/gifs.svelte';
	import { focusTrap } from '$lib/actions/focusTrap';

	interface Props {
		onSelect: (gif: { url: string; previewUrl: string; width?: number; height?: number }) => void;
		onClose?: () => void;
		embedded?: boolean;
	}

	let { onSelect, onClose, embedded = false }: Props = $props();

	let query = $state('');
	let debounceTimer: ReturnType<typeof setTimeout> | null = null;

	function performSearch() {
		gifsStore.load(query, 20);
	}

	function debouncedSearch() {
		if (debounceTimer) clearTimeout(debounceTimer);
		debounceTimer = setTimeout(() => {
			performSearch();
		}, 300);
	}

	function handleSelect(gif: { url: string; previewUrl: string; width?: number; height?: number; title?: string | null }) {
		onSelect({ url: gif.url, previewUrl: gif.previewUrl, width: gif.width ?? undefined, height: gif.height ?? undefined });
		onClose?.();
	}

	$effect(() => {
		void query;
		debouncedSearch();
		return () => {
			if (debounceTimer) clearTimeout(debounceTimer);
		};
	});

	$effect(() => {
		gifsStore.load('', 20);
	});
</script>

<div
	class="gif-picker"
	class:embedded
	aria-label="GIF picker"
	use:focusTrap={{ onEscape: onClose, initialFocus: true }}
>
	{#if !embedded}
		<div class="header">
			<input
				type="text"
				placeholder="Search GIFs..."
				bind:value={query}
				aria-label="Search GIFs"
			/>
			<button class="close-btn" onclick={() => onClose?.()} aria-label="Close GIF picker">
				<svg width="14" height="14" viewBox="0 0 14 14" fill="none" stroke="currentColor" stroke-width="2">
					<path d="M1 1l12 12M13 1L1 13" />
				</svg>
			</button>
		</div>
	{:else}
		<div class="search-wrap">
			<input
				type="text"
				placeholder="Search GIFs..."
				bind:value={query}
				aria-label="Search GIFs"
			/>
		</div>
	{/if}

	<div class="content">
		{#if gifsStore.loading}
			<div class="spinner-wrap">
				<div class="spinner" aria-hidden="true"></div>
				<span class="spinner-text">Loading...</span>
			</div>
		{:else if gifsStore.loaded && gifsStore.results.length === 0}
			<div class="empty">No results</div>
		{:else}
			<div class="grid">
				{#each gifsStore.results as gif (gif.id)}
					<button
						class="gif-btn"
						onclick={() =>
							handleSelect({
								url: gif.url,
								previewUrl: gif.previewUrl,
								width: gif.width ?? undefined,
								height: gif.height ?? undefined,
								title: gif.title
							})}
						aria-label="Select GIF: {gif.title ?? 'Untitled'}"
						type="button"
					>
						<img
							src={gif.previewUrl}
							alt={gif.title ?? ''}
							loading="lazy"
						/>
					</button>
				{/each}
			</div>
		{/if}
	</div>
</div>

<style>
	.gif-picker {
		background: var(--p-surface-2);
		border: 1px solid var(--p-line);
		border-radius: var(--radius-lg);
		padding: var(--space-md);
		max-height: 400px;
		overflow-y: auto;
		display: flex;
		flex-direction: column;
		width: 320px;
	}

	.gif-picker.embedded {
		background: transparent;
		border: none;
		border-radius: 0;
		padding: 0;
		width: 100%;
		max-height: 360px;
	}

	.header {
		display: flex;
		align-items: center;
		gap: var(--space-sm);
		margin-bottom: var(--space-md);
		flex-shrink: 0;
	}

	.header input,
	.search-wrap input {
		flex: 1;
		background: var(--p-bg);
		border: 1px solid var(--p-line);
		border-radius: var(--radius-pill);
		padding: var(--space-sm) var(--space-md);
		color: var(--p-text);
		font-size: var(--text-sm);
		outline: none;
	}

	.header input:focus,
	.search-wrap input:focus {
		border-color: var(--p-accent);
	}

	.search-wrap {
		margin-bottom: var(--space-md);
		flex-shrink: 0;
	}

	.search-wrap input {
		width: 100%;
		box-sizing: border-box;
	}

	.close-btn {
		background: none;
		border: none;
		color: var(--p-text-2);
		cursor: pointer;
		padding: var(--space-xs);
		border-radius: var(--radius-sm);
		transition: background 0.1s;
		flex-shrink: 0;
		display: flex;
		align-items: center;
		justify-content: center;
	}

	.close-btn:hover {
		background: var(--p-surface);
	}

	.content {
		flex: 1;
		min-height: 0;
		overflow-y: auto;
	}

	.grid {
		display: grid;
		grid-template-columns: repeat(3, 1fr);
		gap: var(--space-sm);
	}

	.gif-btn {
		background: none;
		border: none;
		padding: 0;
		cursor: pointer;
		border-radius: var(--radius-md);
		overflow: hidden;
		aspect-ratio: 16 / 10;
		transition: transform 0.1s;
	}

	.gif-btn:hover {
		transform: scale(1.02);
	}

	.gif-btn img {
		width: 100%;
		height: 100%;
		object-fit: cover;
		display: block;
	}

	.spinner-wrap {
		display: flex;
		flex-direction: column;
		align-items: center;
		justify-content: center;
		padding: var(--space-lg);
		gap: var(--space-sm);
	}

	.spinner {
		width: 24px;
		height: 24px;
		border: 2px solid var(--p-line);
		border-top-color: var(--p-accent);
		border-radius: 50%;
		animation: spin 0.8s linear infinite;
	}

	.spinner-text {
		color: var(--p-text-2);
		font-size: var(--text-sm);
	}

	.empty {
		padding: var(--space-lg);
		text-align: center;
		color: var(--p-text-2);
		font-size: var(--text-sm);
	}

	@keyframes spin {
		to {
			transform: rotate(360deg);
		}
	}

	@media (max-width: 767px) {
		.gif-picker:not(.embedded) {
			width: calc(100vw - 2 * var(--space-lg));
		}

		.grid {
			grid-template-columns: repeat(auto-fill, minmax(120px, 1fr));
		}
	}
</style>
