// apps/web/src/lib/components/MessageComposer.svelte
<script lang="ts">
	import Icon from './Icon.svelte';

	interface Props {
		onSend?: (content: string) => void;
		onTypingStart?: () => void;
		onTypingStop?: () => void;
		disabled?: boolean;
	}

	let { onSend, onTypingStart, onTypingStop, disabled = false }: Props = $props();

	let content = $state('');
	let typingTimer = $state<ReturnType<typeof setTimeout> | null>(null);

	function handleInput() {
		onTypingStart?.();
		if (typingTimer) clearTimeout(typingTimer);
		typingTimer = setTimeout(() => {
			onTypingStop?.();
		}, 2000);
	}

	function handleSubmit(e: Event) {
		e.preventDefault();
		const trimmed = content.trim();
		if (!trimmed || disabled) return;
		onSend?.(trimmed);
		content = '';
		if (typingTimer) clearTimeout(typingTimer);
		onTypingStop?.();
	}
</script>

<form class="composer" onsubmit={handleSubmit}>
	<input
		type="text"
		placeholder="Message..."
		bind:value={content}
		oninput={handleInput}
		disabled={disabled}
	/>
	<button type="submit" disabled={disabled || !content.trim()} aria-label="Send message">
		<Icon name="send" size={20} />
	</button>
</form>

<style>
	.composer {
		display: flex;
		align-items: center;
		gap: var(--space-sm);
		padding: var(--space-sm) var(--space-lg);
		padding-bottom: calc(var(--space-sm) + env(safe-area-inset-bottom));
		border-top: 1px solid var(--color-border);
		background: var(--color-surface);
	}

	input {
		flex: 1;
		background: var(--color-bg);
		border: 1px solid var(--color-border);
		border-radius: var(--radius-pill);
		color: var(--color-text);
		padding: var(--space-sm) var(--space-md);
		font-size: var(--text-base);
		font-family: inherit;
		outline: none;
	}

	input:focus { border-color: var(--color-accent); }
	input:disabled { opacity: 0.5; }

	button {
		width: 40px;
		height: 40px;
		border-radius: 50%;
		background: var(--color-accent);
		color: var(--color-bg);
		border: none;
		display: flex;
		align-items: center;
		justify-content: center;
		cursor: pointer;
		transition: opacity 0.15s;
		flex-shrink: 0;
	}

	button:disabled {
		opacity: 0.35;
		cursor: not-allowed;
	}

	button:not(:disabled):hover {
		opacity: 0.85;
	}
</style>

// apps/mobile/src/components/MessageComposer.vue
<template>
  <div class="composer-container">
    <textarea 
      v-model="draft" 
      rows="2" 
      placeholder="Type a message..."
      :disabled="disabled"
      enterkeyhint="send"
      @keydown.enter.exact.prevent="handleEnter"
    ></textarea>
    <div class="actions">
      <button 
        class="send-btn" 
        :disabled="disabled || !draft.trim()" 
        @click="send"
      >
        Send
      </button>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';

defineProps<{
  disabled: boolean;
}>();

const emit = defineEmits<{
  (e: 'send', content: string): void;
}>();

const draft = ref('');

function send() {
  const content = draft.value.trim();
  if (!content) return;
  emit('send', content);
  draft.value = '';
}

function handleEnter(e: KeyboardEvent) {
  // Shift+Enter for newline, Enter to send
  if (!e.shiftKey) {
    send();
  }
}
</script>

<style scoped>
.composer-container {
  display: flex;
  gap: 12px;
  align-items: flex-end;
  background: var(--panel-2);
  padding: 12px;
  border-radius: 12px;
  border: 1px solid rgba(255, 255, 255, 0.05);
}

textarea {
  flex: 1;
  resize: none;
  background: rgba(15, 18, 34, 0.6);
  border: 1px solid rgba(255, 255, 255, 0.1);
  padding: 10px 14px;
  border-radius: 16px;
  font-family: inherit;
  color: var(--text);
  line-height: 1.4;
}

textarea:focus {
  outline: none;
  border-color: var(--accent);
}

.send-btn {
  height: 44px;
  padding: 0 20px;
  border-radius: 16px;
  background: var(--accent);
  color: #041027;
  font-weight: 700;
  border: none;
  cursor: pointer;
  transition: opacity 0.2s;
}

.send-btn:disabled {
  opacity: 0.5;
  cursor: not-allowed;
  background: rgba(255, 255, 255, 0.2);
  color: rgba(255, 255, 255, 0.5);
}
</style>
